[UI]
# Name of the app and chatbot.
name = "AI Elevator Pitch Tutor"

# Description of the app and chatbot. This is used for HTML tags.
description = "Your personal AI tutor for crafting the perfect elevator pitch"

# Show the readme while the chat is empty.
show_readme_as_default = true

# Hide the chain of thought toggle.
hide_cot = true

# Input placeholder
input_placeholder = "Type your message here..."

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages. This can be a security risk
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    # Define accepted file types using MIME types
    accept = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]
    max_files = 5
    max_size_mb = 20

[data]
# Use the official PostgreSQL data layer
provider = "postgresql"

# Authentication is disabled for simplicity
# [auth]
# type = "password"
# requires_login = true
